### ISSUE TITLE
Hiba: A saját telkemen nem tudok aludni 

### ISSUE THREAD

**Issue by Zoflika** [liquidmasters/Szerver#6]
# Hiba bejelentés

Megpróbáltam a saját ágyammal aludni a saját town-omban de nem tudtam. 

1. Letettem egy ágyat a saját telkemen.
2. Rányomtam a jobb egér gombbal.
3. Egy hibát ír ki is nem tudok aludni.

A saját telkemen kellett volna aludnom. 

![image](https://user-images.githubusercontent.com/80456836/110773729-56841c00-825d-11eb-88f5-1e77172fca95.png)

**Comment by Laci444** [comment]
Ezt egyelőre még nem javítom, mert ennek inkább egy nehezítésnek kellene lennie, nem bugnak. Ha a későbbi tesztelési fázisnál is zavaró lesz nyissatok újra issue-t és megdumáljuk
