### ISSUE TITLE
Javaslat: Local chat

### ISSUE THREAD

**Issue by szabodani04** [liquidmasters/Szerver#7]
# Feljesztési javaslat
**Platform**
Minecraft server

**Az ötlet részletezése**
Nem lenne rossz a local chat vagy akár valami friend chat, ami olyan lenne hogy be tudod friendelni a másikat és akkor velük beszélgetni a chaten.

**Egyéb hozzáfűznivaló**

**Comment by Laci444** [comment]
/m: privát üzenet
/tc vagy /város: a város chat
/nc vagy /nemzet: nemzet chat
/ac vagy /szövetség: szövetség chat
kell még más?
