### ISSUE TITLE
Hiba: Tab

### ISSUE THREAD

**Issue by szabodani04** [liquidmasters/Szerver#9]
# Hiba bejelentés

**A hiba leírása**
A tabban a weblap címe a liquidmasters.hu a www.liquidmasters.hu az weblaposíbban hangzik
![image](https://user-images.githubusercontent.com/71460088/110858215-18691580-82ba-11eb-8c40-7e8ec9f2c984.png)

**Comment by Laci444** [comment]
javítottam
